/**
 * @fileoverview Master index for DiscoveryOS core package.
 * Re-exports all modules for convenient importing throughout the application.
 */

// Enums
export {
  DocumentStatusEnum,
  EvidenceTypeEnum,
  OpportunityPriorityEnum,
  AgentNameEnum,
  SourceTypeEnum,
  ProcessingStatusEnum,
  LanguageEnum,
  type DocumentStatus,
  type EvidenceType,
  type OpportunityPriority,
  type AgentName,
  type SourceType,
  type ProcessingStatus,
  type Language,
} from "./types/enums.js";

// Constants
export {
  SUPPORTED_FILE_TYPES,
  SUPPORTED_MIME_TYPES,
  MAX_UPLOAD_SIZE_MB,
  MAX_UPLOAD_SIZE_BYTES,
  DEFAULT_CHUNK_SIZE,
  DEFAULT_CHUNK_OVERLAP,
  SUPPORTED_LANGUAGES,
  CONFIDENCE_THRESHOLDS,
  DEFAULT_CONFIDENCE_SCORE,
  AGENT_EXECUTION_ORDER,
  SCHEMA_VERSION,
  APP_VERSION,
  MAX_PROCESSING_RETRIES,
  DEFAULT_AGENT_TIMEOUT_MS,
  MIN_EVIDENCE_FOR_INSIGHT,
  MIN_INSIGHTS_FOR_THEME,
  MAX_THEMES_PER_OPPORTUNITY,
  MAX_OPPORTUNITIES_PER_REPORT,
} from "./utils/constants.js";

// Types
export type {
  UUID,
  ISODate,
  Timestamp,
  Email,
  URL,
  ConfidenceScore,
  DocumentStatusType,
  EvidenceTypeValue,
  OpportunityPriorityValue,
  AgentNameValue,
  SourceTypeValue,
  ProcessingStatusValue,
  LanguageValue,
  Metadata,
  ChunkMetadata,
  EmbeddingReference,
  AnalysisSummary,
  Relationship,
  RelationshipContext,
  PaginationMetadata,
  ValidationError,
  ProcessingError,
  AnalysisError,
  AgentError,
  SuccessResult,
  FailureResult,
  Result,
  DomainError,
} from "./types/index.js";

export {
  Ok,
  Err,
  isSuccess,
  isFailure,
  unwrap,
  getError,
  map,
  flatMap,
} from "./types/index.js";

// Utilities
export {
  generateUUID,
  generateUUIDv5,
  isValidUUID,
  asUUID,
  createDeterministicUUID,
  generateUUIDs,
  getCurrentISODate,
  getCurrentTimestamp,
  formatISODate,
  parseISODate,
  timestampToISODate,
  isoDateToTimestamp,
  isPastDate,
  isFutureDate,
  getDateDifference,
  isSameDay,
  addDays,
  addHours,
  getStartOfDay,
  getEndOfDay,
  createConfidenceScore,
  isValidConfidenceScore,
  getConfidenceLevel,
  meetsThreshold,
  averageConfidenceScores,
  weightedConfidenceAverage,
  combineConfidenceScores,
  isHighConfidence,
  isBelowThreshold,
  validateEmail,
  validateURL,
  isNonEmptyString,
  isValidJSON,
  isNonEmptyArray,
  isArraySizeValid,
  isNumberInRange,
  matchesPattern,
  hasRequiredKeys,
  isValidUUIDFormat,
  isPositiveInteger,
  isNonNegativeInteger,
  hasKey,
  buildRelationship,
  linkToDocument,
  linkToEvidence,
  linkToInsight,
  linkToTheme,
  linkToOpportunity,
  isValidRelationship,
  getRelationshipsByType,
  collectTargetIds,
  sortByStrength,
  filterByStrength,
  getStrongestRelationship,
  buildRelationshipGraph,
} from "./utils/index.js";

// Schemas
export {
  DocumentSchema,
  EvidenceSchema,
  InsightSchema,
  ThemeSchema,
  OpportunitySchema,
  ReportSchema,
  type Document,
  type Evidence,
  type Insight,
  type Theme,
  type Opportunity,
  type Report,
} from "./schemas/index.js";

// Database Entities
export type {
  DocumentEntity,
  EvidenceEntity,
  InsightEntity,
  ThemeEntity,
  OpportunityEntity,
  ReportEntity,
} from "./database/index.js";
