import { Topbar } from "@/components/layout/Topbar";
import { ReportsList } from "@/components/reports/ReportsList";
import { getReports } from "@/lib/api";
import { Sparkles } from "lucide-react";

export const dynamic = "force-dynamic";

export default async function ReportsPage() {
  const data = await getReports();

  return (
    <>
      <Topbar breadcrumb="Reports" actionLabel="Generate Report" actionIcon={<Sparkles size={16} />} />

      <main className="flex-1 overflow-y-auto px-6 py-6">
        <div className="mx-auto flex max-w-[1400px] flex-col gap-6">
          <div>
            <h1 className="text-[22px] font-bold text-ink-900">Reports</h1>
            <p className="mt-1 text-[13.5px] text-ink-500">
              {data.total} reports generated by the Report Agent, ready to share with stakeholders
            </p>
          </div>

          <ReportsList reports={data.reports} />
        </div>
      </main>
    </>
  );
}
